export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const RESET = 'RESET';
